//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceQA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceQA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebDox.ResourceQA", typeof(ResourceQA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato generado desde portal finastrategy para divulgacion de informacion sensible con el usuario.
        /// </summary>
        internal static string Configuration_DefaultWorkflowDescription {
            get {
                return ResourceManager.GetString("Configuration.DefaultWorkflowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Contrato NDA Finastrategy.
        /// </summary>
        internal static string Configuration_DefaultWorkflowName {
            get {
                return ResourceManager.GetString("Configuration.DefaultWorkflowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51103434-8dd8-4a5f-ad73-dfdb4758a382.
        /// </summary>
        internal static string Configuration_FormIdNDA {
            get {
                return ResourceManager.GetString("Configuration.FormIdNDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Configuration_StepSigner {
            get {
                return ResourceManager.GetString("Configuration.StepSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string Credential_GranttypeService {
            get {
                return ResourceManager.GetString("Credential.GranttypeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin123123.
        /// </summary>
        internal static string Credential_PasswordService {
            get {
                return ResourceManager.GetString("Credential.PasswordService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carlos.cicler@finastrategy.mx.
        /// </summary>
        internal static string Credential_UsernameService {
            get {
                return ResourceManager.GetString("Credential.UsernameService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0b65b7e2-7f8d-4db6-959f-858f82835788.
        /// </summary>
        internal static string Field_Address1 {
            get {
                return ResourceManager.GetString("Field.Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f52d4dea-884e-468d-81a0-260f5e86c282.
        /// </summary>
        internal static string Field_Address2 {
            get {
                return ResourceManager.GetString("Field.Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9f74c0ca-733a-443b-ae63-1cd64cb0e719.
        /// </summary>
        internal static string Field_Birthday {
            get {
                return ResourceManager.GetString("Field.Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0c7ce929-2715-4abd-8edb-38b02e084461.
        /// </summary>
        internal static string Field_Cellphone {
            get {
                return ResourceManager.GetString("Field.Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90f04efe-772f-4af7-bc4d-37d6704cd8bc.
        /// </summary>
        internal static string Field_CurrentDate {
            get {
                return ResourceManager.GetString("Field.CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3d969c3d-ed3d-4b66-ab55-8c06ed283e72.
        /// </summary>
        internal static string Field_Email {
            get {
                return ResourceManager.GetString("Field.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12b4a060-b376-43ab-b999-4648e1c507a0.
        /// </summary>
        internal static string Field_EntityBirth {
            get {
                return ResourceManager.GetString("Field.EntityBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 78cb6474-bb27-4d69-bc7f-9d1f7a43af85.
        /// </summary>
        internal static string Field_ExpeditionPlace {
            get {
                return ResourceManager.GetString("Field.ExpeditionPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e7ab7d41-9b27-485f-954a-a9a976a60831.
        /// </summary>
        internal static string Field_Fullname {
            get {
                return ResourceManager.GetString("Field.Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8d209fae-5c89-4fa2-ac6b-bb04dff2689a.
        /// </summary>
        internal static string Field_Occupation {
            get {
                return ResourceManager.GetString("Field.Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 89c5ef22-6d65-400f-9031-5193b0be212f.
        /// </summary>
        internal static string Field_RFC {
            get {
                return ResourceManager.GetString("Field.RFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com/api/v2/documents.
        /// </summary>
        internal static string Service_AddDocument {
            get {
                return ResourceManager.GetString("Service.AddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com.
        /// </summary>
        internal static string Service_BaseUrl {
            get {
                return ResourceManager.GetString("Service.BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com/api/v2/oauth/token.
        /// </summary>
        internal static string Service_Login {
            get {
                return ResourceManager.GetString("Service.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com/api/v2/workflow_requests.
        /// </summary>
        internal static string Service_NewRequest {
            get {
                return ResourceManager.GetString("Service.NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com/api/v2/decision_workflows/{0}/steps/{1}/signers?parallel_number=0.
        /// </summary>
        internal static string Service_Signer {
            get {
                return ResourceManager.GetString("Service.Signer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com/api/v2/decision_workflows/{0}/validate?number={1}&amp;parallel_number=0.
        /// </summary>
        internal static string Service_StartCelebration {
            get {
                return ResourceManager.GetString("Service.StartCelebration", resourceCulture);
            }
        }
    }
}
