//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcePROD {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePROD() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebDox.ResourcePROD", typeof(ResourcePROD).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato generado desde portal finastrategy para divulgacion de informacion sensible con el usuario.
        /// </summary>
        internal static string Configuration_DefaultWorkflowDescription {
            get {
                return ResourceManager.GetString("Configuration.DefaultWorkflowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Contrato NDA Finastrategy.
        /// </summary>
        internal static string Configuration_DefaultWorkflowName {
            get {
                return ResourceManager.GetString("Configuration.DefaultWorkflowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51103434-8dd8-4a5f-ad73-dfdb4758a382.
        /// </summary>
        internal static string Configuration_FormIdNDA {
            get {
                return ResourceManager.GetString("Configuration.FormIdNDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Configuration_StepSigner {
            get {
                return ResourceManager.GetString("Configuration.StepSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string Credential_GranttypeService {
            get {
                return ResourceManager.GetString("Credential.GranttypeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^gJh9pK#mL4qW$3fTz%y*1xNt2.
        /// </summary>
        internal static string Credential_PasswordService {
            get {
                return ResourceManager.GetString("Credential.PasswordService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.fina@finastrategy.mx.
        /// </summary>
        internal static string Credential_UsernameService {
            get {
                return ResourceManager.GetString("Credential.UsernameService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c243db8d-559b-43a1-85bc-6857fc9977c4.
        /// </summary>
        internal static string Field_Address1 {
            get {
                return ResourceManager.GetString("Field.Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f52d4dea-884e-468d-81a0-260f5e86c282.
        /// </summary>
        internal static string Field_Address2 {
            get {
                return ResourceManager.GetString("Field.Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 248ceb2d-25f9-4b31-949b-e0985417a70f.
        /// </summary>
        internal static string Field_Birthday {
            get {
                return ResourceManager.GetString("Field.Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f0dac901-2229-446b-a266-97303b7d33c4.
        /// </summary>
        internal static string Field_Cellphone {
            get {
                return ResourceManager.GetString("Field.Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4438547c-da87-450b-a53b-b19487af5116.
        /// </summary>
        internal static string Field_CurrentDate {
            get {
                return ResourceManager.GetString("Field.CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8a58b8f7-e93d-4065-8c28-500ffa5ad593.
        /// </summary>
        internal static string Field_Email {
            get {
                return ResourceManager.GetString("Field.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2a3ba0bf-ed97-41b7-9905-64d3d745e0b3.
        /// </summary>
        internal static string Field_EntityBirth {
            get {
                return ResourceManager.GetString("Field.EntityBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b68e7c3f-3be2-4d31-83bf-d9d1359bdc0f.
        /// </summary>
        internal static string Field_ExpeditionPlace {
            get {
                return ResourceManager.GetString("Field.ExpeditionPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5e242277-c5ed-4f9e-a263-7d286db22f63.
        /// </summary>
        internal static string Field_Fullname {
            get {
                return ResourceManager.GetString("Field.Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c1de68f7-8b2a-4838-a851-06cdabd225b7.
        /// </summary>
        internal static string Field_Occupation {
            get {
                return ResourceManager.GetString("Field.Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d3d209c4-3ea5-41e1-8c04-eafebe227092.
        /// </summary>
        internal static string Field_RFC {
            get {
                return ResourceManager.GetString("Field.RFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com/api/v2/documents.
        /// </summary>
        internal static string Service_AddDocument {
            get {
                return ResourceManager.GetString("Service.AddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com.
        /// </summary>
        internal static string Service_BaseUrl {
            get {
                return ResourceManager.GetString("Service.BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com/api/v2/oauth/token.
        /// </summary>
        internal static string Service_Login {
            get {
                return ResourceManager.GetString("Service.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com/api/v2/workflow_requests.
        /// </summary>
        internal static string Service_NewRequest {
            get {
                return ResourceManager.GetString("Service.NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com/api/v2/decision_workflows/{0}/steps/{1}/signers?parallel_number=0.
        /// </summary>
        internal static string Service_Signer {
            get {
                return ResourceManager.GetString("Service.Signer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://app.webdoxclm.com/api/v2/decision_workflows/{0}/validate?number={1}&amp;parallel_number=0.
        /// </summary>
        internal static string Service_StartCelebration {
            get {
                return ResourceManager.GetString("Service.StartCelebration", resourceCulture);
            }
        }
    }
}
