//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessLogic.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error.
        /// </summary>
        internal static string signinuserservice_addnewuser_exception {
            get {
                return ResourceManager.GetString("signinuserservice_addnewuser_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario ya registrado, intenta recuperar tu contraseña o registra uno nuevo .
        /// </summary>
        internal static string signinuserservice_addnewuser_fail {
            get {
                return ResourceManager.GetString("signinuserservice_addnewuser_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha generado un nuevo usuario {0}.
        /// </summary>
        internal static string signinuserservice_addnewuser_success {
            get {
                return ResourceManager.GetString("signinuserservice_addnewuser_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error.
        /// </summary>
        internal static string signinuserservice_passwordrecovery_exception {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecovery_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al intentar genrar una recuperacion de password del usuario {0}.
        /// </summary>
        internal static string signinuserservice_passwordrecovery_exception_log {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecovery_exception_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperacion no enviada.
        /// </summary>
        internal static string signinuserservice_passwordrecovery_fail {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecovery_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de envio de recuperacion de contrasena fallida para el usuario {0}.
        /// </summary>
        internal static string signinuserservice_passwordrecovery_fail_log {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecovery_fail_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string signinuserservice_passwordrecovery_invalid {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecovery_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string signinuserservice_passwordrecovery_invalid_log {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecovery_invalid_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperacion enviada.
        /// </summary>
        internal static string signinuserservice_passwordrecovery_success {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecovery_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado la recuperacion de contrasena para el usuario {0}.
        /// </summary>
        internal static string signinuserservice_passwordrecovery_success_log {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecovery_success_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de actualizacion fallido, ha ocurrido un error.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_exception {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de actualizacion de contrasena fallida para el usuario {0} - catch.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_exception_log {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_exception_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ralizo el cambio de contraseña, ha ocurrido un error.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_fail {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de actualizacion de contrasena fallido al guardar del usuario {0}.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_fail_log {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_fail_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion no valida.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_invalid {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de validacion de recuperacion de contrasena con un celular no valido: {0}.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_invalid_log {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_invalid_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta esuna peticion invalida, intentalo nuevamente.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_invalid2 {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_invalid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de recuperacion de contrasena sin peticion registrada para el celular {0}.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_invalid2_log {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_invalid2_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peticion invalida, intentalo nuevamente.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_invalid3 {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_invalid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de validacion de codigo de mensaje, resultado no exitoso: {0}.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_invalid3_log {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_invalid3_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de contraseña se ha realizado con exito.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_success {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de contraseña se ha realizado con exito para el usuario {0}.
        /// </summary>
        internal static string signinuserservice_passwordrecoveryvalidate_success_log {
            get {
                return ResourceManager.GetString("signinuserservice_passwordrecoveryvalidate_success_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error.
        /// </summary>
        internal static string signinuserservice_sendcodesms_exception {
            get {
                return ResourceManager.GetString("signinuserservice_sendcodesms_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string signinuserservice_sendcodesms_fail {
            get {
                return ResourceManager.GetString("signinuserservice_sendcodesms_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion no valida.
        /// </summary>
        internal static string signinuserservice_sendcodesms_invalid {
            get {
                return ResourceManager.GetString("signinuserservice_sendcodesms_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de envio de sms de registro fallido para el numero: {0}.
        /// </summary>
        internal static string signinuserservice_sendcodesms_invalid_log {
            get {
                return ResourceManager.GetString("signinuserservice_sendcodesms_invalid_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje enviado.
        /// </summary>
        internal static string signinuserservice_sendcodesms_success {
            get {
                return ResourceManager.GetString("signinuserservice_sendcodesms_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error.
        /// </summary>
        internal static string signinuserservice_userinformation_exception {
            get {
                return ResourceManager.GetString("signinuserservice_userinformation_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al tratar de obtener informacion de usuario {0}.
        /// </summary>
        internal static string signinuserservice_userinformation_exception_log {
            get {
                return ResourceManager.GetString("signinuserservice_userinformation_exception_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion de usuario no encontrada.
        /// </summary>
        internal static string signinuserservice_userinformation_fail {
            get {
                return ResourceManager.GetString("signinuserservice_userinformation_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion de usuario no encontrada de usuario {0}.
        /// </summary>
        internal static string signinuserservice_userinformation_fail_log {
            get {
                return ResourceManager.GetString("signinuserservice_userinformation_fail_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos invalidos.
        /// </summary>
        internal static string signinuserservice_userinformation_invalid {
            get {
                return ResourceManager.GetString("signinuserservice_userinformation_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de obtener informacion del usuario {0} fallida.
        /// </summary>
        internal static string signinuserservice_userinformation_invalid_log {
            get {
                return ResourceManager.GetString("signinuserservice_userinformation_invalid_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion encontrada.
        /// </summary>
        internal static string signinuserservice_userinformation_success {
            get {
                return ResourceManager.GetString("signinuserservice_userinformation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La validacion no ha sido exitosa.
        /// </summary>
        internal static string signinuserservice_validatesmscode_fail {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscode_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion no valida.
        /// </summary>
        internal static string signinuserservice_validatesmscode_invalid {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscode_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de validacion de registro fallido para el numero {0}.
        /// </summary>
        internal static string signinuserservice_validatesmscode_invalid_log {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscode_invalid_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se valido correctamente el numero telefonico.
        /// </summary>
        internal static string signinuserservice_validatesmscode_success {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscode_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error.
        /// </summary>
        internal static string signinuserservice_validatesmscodepasswordrecovery_exception {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscodepasswordrecovery_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exception  al validar codigo de sms del usuario {0}.
        /// </summary>
        internal static string signinuserservice_validatesmscodepasswordrecovery_exception_log {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscodepasswordrecovery_exception_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La validacion no ha sido exitosa.
        /// </summary>
        internal static string signinuserservice_validatesmscodepasswordrecovery_fail {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscodepasswordrecovery_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo recibido en el celular {0} no es valido.
        /// </summary>
        internal static string signinuserservice_validatesmscodepasswordrecovery_fail_log {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscodepasswordrecovery_fail_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion no valida.
        /// </summary>
        internal static string signinuserservice_validatesmscodepasswordrecovery_invalid {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscodepasswordrecovery_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intento de validacion de registro fallido para el numero: {0}.
        /// </summary>
        internal static string signinuserservice_validatesmscodepasswordrecovery_invalid_log {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscodepasswordrecovery_invalid_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se valido correctamente el codigo.
        /// </summary>
        internal static string signinuserservice_validatesmscodepasswordrecovery_success {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscodepasswordrecovery_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validacion de codigo de recuperacion de contrasena validado: {0}.
        /// </summary>
        internal static string signinuserservice_validatesmscodepasswordrecovery_success_log {
            get {
                return ResourceManager.GetString("signinuserservice_validatesmscodepasswordrecovery_success_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta de envio de mesaje: {0}.
        /// </summary>
        internal static string smsservice_sendsmsotp_success {
            get {
                return ResourceManager.GetString("smsservice_sendsmsotp_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta validacion sms {0}.
        /// </summary>
        internal static string smsservice_validatesmsotp_success {
            get {
                return ResourceManager.GetString("smsservice_validatesmsotp_success", resourceCulture);
            }
        }
    }
}
